[build]
# target = ["riscv64gc-unknown-none-elf"]
target = ["loongarch64-unknown-none"]

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"
]
