[package]
name = "os"
version = "0.1.0"
authors = ["Yao Junjie <345024941@qq.com>"]
edition = "2021"

[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
buddy_system_allocator = "0.11.0"
bitflags = "2.8.0"
xmas-elf = "0.9.1"
virtio-drivers = { path = "../vendor/virtio-drivers" }
# simple-fat32 = { path = "../simple-fat32" }
log = "0.4"
sbi-rt = { version = "0.0.3", features = ["legacy"] }
spin = "0.9.8"
sbi-spec = "0.0.8"
num_enum = { version = "0.7.2", default-features = false }
zerocopy = { version = "0.8.21", features = ["derive"]}
lwext4_rust= {path = "../lwext4_rust"}
hashbrown = "0.15.2"

[features]
board_qemu = []
default = ["info", "test", "mul_hart"]
error = []
warn = []
info = []
debug = []
trace = []
mul_hart = []
test = []

[profile.release]
debug = true